on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

env:
  PHP_EXTENSIONS: intl, pcov
  PHP_VERSION: 8.3

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install packages
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: ghostscript
          version: 1

      - name: Setup PHP extensions cache
        id: php-extensions-cache
        uses: shivammathur/cache-extensions@v1
        with:
          php-version: ${{ env.PHP_VERSION }}
          extensions: ${{ env.PHP_EXTENSIONS }}
          key: ${{ runner.os }}-PHP-Extensions-V1

      - name: Cache PHP extensions
        uses: actions/cache@v4
        with:
          path: ${{ steps.php-extensions-cache.outputs.dir }}
          key: ${{ steps.php-extensions-cache.outputs.key }}
          restore-keys: ${{ steps.php-extensions-cache.outputs.key }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
          extensions: ${{ env.PHP_EXTENSIONS }}

      - name: Get Composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
        
      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-Composer-V1-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-Composer-V1-

      - name: Install Composer dependencies
        run: composer update --prefer-dist --prefer-stable --no-progress

      - name: Run PHPUnit tests
        run: vendor/bin/phpunit --coverage-clover=coverage.clover --coverage-text
      
      - name: Upload coverage to Scrutinizer
        run: vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover
